version: "3.3"

services:

  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    ports:
      - "8080:80" #web
      - "8081:8080" #dashboard
      - "443:443" #secureweb
      
   volumes:
      - /srv/Traefik:/srv/Traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/Traefik:/srv/Traefik

 whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`villafeliz.online`)"
      - "traefik.http.routers.whoami.entrypoints=web"
